### ISSUE TITLE
Create script that produces a list of links rather than raw data

### ISSUE THREAD

**Issue by sdruskat** [sdruskat/cff-in-the-wild#19]
As the data in CFF files are partly personal data, we don't want to provide a dataset with raw CFF files. Instead, the dataset should be a list of links to CFF files that can be retrieved via a simple script.

This issue is for the creation of that script :).

**Comment by sdruskat** [comment]
Should work (if the GitHub API does) without authentication, but should also provide a `--token` argument for people that have one/want to use one for better rate limits.

**Comment by Bisaloo** [comment]
Fixed in #25
